README.md

At least on windows and linux the
README.md example test case does not work.
The Get Value From Set keywords requires
that the value is written in lower case.

Fixed README.md example test case.

---

pabot/pabot.py

Fixes [pabot-28] (https://github.com/mkorpela/pabot/issues/28).

[pabot-28] Set `.` to be default directory when `-d or --outputdir` not specified

---

README.md
pabot/PabotLib.py
pabot/pabot.py

Use one PabotLib remote library instance from multiple Robot Framework
test runner instances. This enables the resource sharing and locking
between multiple testers. The resources could be for example servers to
be tested or usernames to use in tests for specific server.

Enable resource locking between instances

---

pabot/result_merger.py

Fix issue #52 with module import when using pabot with Robot Framework 3.0 and one pep8 related fix (two blank lines before class).
Tested with RF versions 2.9.2 and 3.0b1

Fix issue #52

---

pabot/pabot.py

Only append PABOTLIBURI variable to options['variable'] once.

Fix for Issue #58

---

pabot/pabot.py

Fix consists of:
1. Forcing timestampoutputs to False when doing the DryRun step of pabot
2. Adding print statements to notify users why get_suite_names returns
an empty list (in case some other issue causes a bad-named XML file like
this one did)

Fix for Issue #56

---

pabot/pabot.py

Hi
this is fix for variable ROBOT_OPTIONS only. As far as I can tell there is no need to pass names of other environment variables (they are handled internally by pybot and not passed as arguments to any methods).
ROBOT_INTERNAL_TRACES - will be inherited by subprocess.
ROBOT_SYSLOG_LEVEL - will be inherited by subprocess.
ROBOT_SYSLOG_FILE - will be inherited by subprocess, but here we have a problem - output file is overridden by each running pybot instance, and then by rebot (I guess when compiling merged output).
Honestly I'm not sure if anyone uses these variables to debug in "pabot" mode.

fix issue #83

---

pabot/result_merger.py

Fix for issue #77. Also avoid merging of base with base (avoids duplicate WARN messages in section 'Test Execution Errors')

fix issue #77

---

pabot/result_merger.py

Now i found the reason, why merging with goup[0] was needed: if a test/suite fails with screenshot, then merging is needed to apply path corrections. I rolled back line 129, but then i need to avoid duplicate WARN msgs again. Thus i added check in line 44...

fix missing screenshot path correction in 1st failing test

---

pabot/pabot.py

1. Commit get rid of extra spaces in verbose mode.
2. Commit improves pabot parallelization using chunksize=1 instead of default.
Problematic was the unspecified chunksize when calling multiprocessing.pool.map_async. This function uses a default chunksize = round_up(suite_count / (processes * 4)).
Now: assume 9 testsuites S1, ..., S9 where execution times of S3 and S4 is 20sec and all others are fast.
If you run pabot with 2 processes p0 and p1 results in chunksize=2 and the list of 9 files is split into chunks:
[S1,S2] via p0 (fast)
[S3,S4] via p1 (slow)
All other chunks are processed via p0 fast.
The problem: When p0 finished all fast chunks, then p0 is idle while p1 is still running S3. S4 is not started on p0, because it is planned for p1 (chunked together with S3)!
Here is a log …

fix extra spaces + better parallelization

---

pabot/pabot.py

How the message writer is just started and then never taken care of again looks a bit unclean.
Coincidentally this fix also fixes #135.

Cleanly stop message writer

---

pabot/pabot.py
setup.py

Solve suite names faster using `robot.running.TestSuiteBuilder` instead of running "dryrun" process for "suite_names.xml" file.
Run "dryrun" suites faster by chunking all available suites for each process. (f.e. 1000 tests on 4 process will run 250 dryrun tests per process)
With this changes dryrun's will run faster than `robot` and prev `pabot` dryrun's.
For example, dry_run for ~3k tests took:
- 25min with these changes
- 60+min without these changes
- 45min using `robot --dryrun`
P.S. `robotframework==3.1.2` was added because `_with_modified_robot` doesn't have compatibility for RF 3.2 and selftests would fail in Travis. You can skip this commit if you have plans adding 3.2 compatibility.

Fast suite solver and fast dry_run

---

pabot/pabot.py

Fixed issue when `pre_run_modifers` won't apply in suite builder

Prerunmodifiers for suite builder fix

---

MANIFEST.in
setup.py

Thanks for pabot!
I'm looking at re-packaging pabot for conda-forge, and noticed the license isn't included in the `sdist`. I'll be able to get it going without (by downloading the license at the right tag, thanks for that!) but it would be ideal if it was included in the future.
This PR adds:
- a `MANIFEST.in`
- the `setup.py` flag to enable picking up the data
Thanks again!

Add LICENSE.txt to source distributions with MANIFEST.in

---

pabot/robotremoteserver.py

The [inspect.getargspec](https://docs.python.org/3/library/inspect.html#inspect.getargspec) is deprecated since python 3.0. With the current code, we can't set some library(e.g. SeleniumLibrary) as SharedLibrary due to below error:
> ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
[inspect.getfullargspec](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec) is fully compatible with the pabot use case.

Replace the deprecated function getargspec to getfullargspec

---

README.md
pabot/arguments.py
pabot/clientwrapper.py
pabot/execution_items.py
pabot/pabot.py
pabot/pabotlib.py

- A new keyword '#DEPENDS' is introduced in the .pabotsuitenames file, enabling declaring tests independent of each other.
- Enable comments in the suite and test items.
- Extract logic to grouping the suites in an extra method.
Address issue #462

Dependency management.

---

pabot/pabotlib.py
tests/fixtures/suite_with_valueset_tags.robot
tests/test_pabot.py
tests/test_pabotlib.py

Enhances the functionality of pabotlib by adding the means of adding valuesets on runtime, without forcing the user to provide the valueset.dat file.
Issue #495

New keyword: "Add Value To Set"

---

pabot/pabot.py
requirements.txt
setup.py
tests/test_testlevelsplit_output_task_order.py

FIxes ordering of testcases in the output files when `--testlevelsplit` option is used by sorting output files with `natsort` before merging them to preserve the correct order of the containing directories.
Issue #493

Fix testlevelsplit output testcase order.

---

src/pabot/SharedLibrary.py
src/pabot/pabotlib.py

This PR addresses the issue raised in #519. 
Please let me know if you have any concerns with my approach or implementation!

Support providing arguments to shared libraries

---

src/pabot/pabot.py
src/pabot/result_merger.py
tests/test_pabot.py

Robot 6.1 introduced a new CLI option `parser` which needs to be added to the list of options not valid for `rebot`. 
In addition Pekka removed the private `_add_initial` from  robot's `NormalizedDict`, he suggests to just leverage `.update()` instead (which also works for older releases).. but maybe you had a reason to use `_add_initial` in the first place? 
Fixes #533

Updates to support Robot 6.1

---

.github/workflows/ci.yml

Extend ci matrix job to include testing against multiple versions of robotframework.
This will be helpful to confirm that the library works with all of the versions documented (and makes it easier to catch problems in future versions).

ci: test against different robotframework versions

---

src/pabot/arguments.py
src/pabot/pabot.py

Resolving deprecation notices (see https://github.com/mkorpela/pabot/issues/539) when using pabot with robotframework (RF) 6.1.
With RF 6.1 it includes more deprecation notices (even for some features that have been deprecated since RF 5.0).
Belows shows example of the deprecation notices as printed on the console prior to this PR.
```
tests/test_pabot.py: 56 warnings
/home/runner/work/pabot/pabot/.tox/py/lib/python3.11/site-packages/robot/utils/argumentparser.py:80: UserWarning: ArgumentParser option 'auto_pythonpath' is deprecated since Robot Framework 5.0.
warnings.warn("ArgumentParser option 'auto_pythonpath' is deprecated "
```
```
tests/test_pabotsuitenames_io.py: 1 warning
/home/runner/work/pabot/pabot/.tox/py/lib/python3.11/site-packages/robot/running/builder/builders.py:112: …
```

fix: exclude deprecated options based on RF version

---

release.sh

- direct invocation of `setup.py` [is deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/)
- publish wheels, so that consumers do not have to build the wheel themselves at every install

publish wheels

---

src/pabot/pabot.py

pabot use TestSuiteBuilder to parse cases before executing. For cases uses other languages, we need to pass language to TestSuiteBuilder so it can handle properly.

Fix error when running non-English robot case files

---

src/pabot/pabot.py
tests/test_prerunmodifier.py

This commit is to fix the fitler failure with dynamic casename or tag, which are generated by prerunmodifier script, in which users can handle the suites or cases witch actual needs, so some of the attributes will be changed.
#606

fix the filter by dynamic case/tag issue

---

src/pabot/result_merger.py
tests/outputs/output_with_latest_robot/first.xml
tests/outputs/output_with_latest_robot/second.xml
tests/outputs/output_with_latest_robot/third.xml
tests/test_resultmerger.py

After robotframework 7.0, the time format of output.xml was changed, end_time is removed and replaced with elapsed, the merger method cannot handle new format correctly, only it picks the elapsed time of first suite fromthe pabot_results as the total elapsed time.
#Fixes593

fix the incorrect elapsed time issue

---

README.md
src/pabot/arguments.py
src/pabot/execution_items.py
src/pabot/pabot.py
tests/test_ordering.py
tests/test_suite_structure.py

- Added a new --no-rebot option that prevents result merging, allowing users to handle it manually later. This was requested in issue #571 to ensure resource availability.
- Added a #SLEEP keyword, which can be used in the --ordering file to introduce delays between subprocess startups. This was requested in issues #500 and #592.
- Fixed a caching mechanism bug related to .pabotsuitenames (#619).
Closes #571, #500, #592, #619. 🚀

feat: Add --no-rebot option and #SLEEP keyword, fix caching bug

---

src/pabot/pabot.py

During dryrun execution item discovery, fix issue that occurs when testlevelsplit is used and therefore the execution items should be of type TestItem and not SuiteItem(s).
Fixes #623

Enable dryrun and testlevelsplit to work together

---

src/pabot/execution_items.py
src/pabot/pabot.py
tests/test_pabot.py

Support the robot framework command line option to re-execute failed test suites
Fixing:
https://github.com/mkorpela/pabot/issues/510
Error Invalid option 'rerunfailedsuites'"
Fixes #510

Support rerunfailedsuites

---

src/pabot/arguments.py
tests/argument_file/arg_case_options.txt
tests/argument_file/arg_mixed_options.txt
tests/argument_file/arg_suite_options.txt
tests/argument_file/suite-1.robot
tests/argument_file/suite-2.robot
tests/argument_file/suite-3.robot
tests/test_arguments_output.py

This commit is to fix the duplicated case runnings with--testlevelsplit option and --argumentfile option in some specific scenarios.
Fixes #515

fix the duplicated running issue with --argumentfile options

---

.github/workflows/update-status-label.yml

This PR introduces a new GitHub Actions workflow that automatically updates the status-type labels (e.g., `status: open`, `status: in progress`, `status: completed`) on issues.
The goal is to ensure issue labels remain in sync with their actual state without requiring manual intervention.
Key points:
- Adds a workflow file under .github/workflows/
- Detects issue activity and updates labels accordingly
- Helps maintain consistency and visibility in issue tracking
Manually updating status labels can be error-prone and time-consuming. Automating this task improves project hygiene and saves contributor time.

Add GitHub workflow to automatically update status-type issue labels
